theme: minima
title: Dennis' awesome github page
author: Dennis Tsui
email: dentsui14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website contains my information.

# social links

show_excerpts: true # set to false to remove excerpts on the homepage
